### ISSUE TITLE
[Enhancement] Remove project naming and examples

### ISSUE THREAD

**Issue by kevinccbsg** [guidesmiths/gs-hygen#11]
When we run the command there are some names that are related to some of our projects.

```
What's the name of your package? Ex: (service he hst results api)
```
We must remove that and add a more open-source example. This it should work for non Guidesmiths projects 👍 

```
What's the name of your package? Ex: (My service api)
```

**Comment by bounteous17** [comment]
https://github.com/infinitaslearning/infinitas-hygen-template-generators/commit/b858724a2c48414d980a8184ee3bc3b91012d1f1
