### ISSUE TITLE
[docs] Improve readme docs

### ISSUE THREAD

**Issue by kevinccbsg** [guidesmiths/gs-hygen#5]
We have to improve readme docs. We must keep clear this **is not** the generator unless it is the cli we use with other hygen templates.

I don't think it is necessary but we could use [Docsify](https://docsify.js.org/#/) to have better documentation.

**Comment by bounteous17** [comment]
https://github.com/guidesmiths/gs-hygen/commit/14c11b3568de0c1f0b7336040a0644630c12a33a
